### ISSUE TITLE
not support edge and google anymore，i remember it works on 2023 year

### ISSUE THREAD

**Issue by nt47** [nefarius/socksifier#5]
### Bug description

my_connect return 0 but crash browser

### Steps to reproduce
i debuged with x64dbg,if disable connect hook , never crash process

hook getlasterror ,crash

### Screenshots

![CAPTURE_20241020_204553](https://github.com/user-attachments/assets/b32cdfb9-1c00-4557-ae8b-d32ec73342eb)  

![CAPTURE_20241020_204917](https://github.com/user-attachments/assets/e37b2deb-d695-4232-9636-157a074a8646)

### Machine info

**CPU-Architecture:** x86, x64, ...
**Windows version:** Windows 11 23H2

### Any other helpful information
but if my_connect return real_connect instead of 0, never crash but recv 404
it works on my C# tools with hook connectEx, i think it is Chrome/edge add some checker

**Comment by nt47** [comment]
close it
connect return 0 change to return SOCKET_ERROR;  all works fine~

**Comment by nefarius** [comment]
What exactly have you changed where and why not PR it so others can profit from the fix?
